Update cart.yaml

diff --git a/.github/workflows/cart.yaml b/.github/workflows/cart.yaml
--- a/.github/workflows/cart.yaml
+++ b/.github/workflows/cart.yaml
@@ -32,6 +32,14 @@ jobs:
         uses: actions/setup-node@v3
         with:
           node-version: '14'
+          
+      - name: Ensure Dockerfile exists
+        run: |
+          if [ ! -f ./cart/Dockerfile ]; then
+            echo "Dockerfile not found in the cart directory."
+            exit 1
+          fi
+          echo "Dockerfile exists, proceeding with build."
 
       - name: Login to Docker Hub
         uses: docker/login-action@v3
